"""Sync models with schema

Revision ID: 10e0c2300ad3
Revises: 4cf49fd6d0cb
Create Date: 2026-02-22 12:53:35.042426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e0c2300ad3'
down_revision: Union[str, Sequence[str], None] = '4cf49fd6d0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'question_id', name='uq_test_question')
    )
    op.add_column('programs', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('programs', sa.Column('mode', sa.String(), nullable=False))
    op.add_column('programs', sa.Column('topics', sa.JSON(), nullable=False))
    op.add_column('programs', sa.Column('benefits', sa.JSON(), nullable=False))
    op.add_column('tests', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'description')
    op.drop_column('programs', 'benefits')
    op.drop_column('programs', 'topics')
    op.drop_column('programs', 'mode')
    op.drop_column('programs', 'duration')
    op.drop_table('test_questions')
    # ### end Alembic commands ###
