"""Add question_draft_batches, question_drafts, practice_sets tables

Revision ID: 98aedfb8403c
Revises: e72174d60e7b
Create Date: 2026-03-03 14:14:25.276909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98aedfb8403c'
down_revision: Union[str, Sequence[str], None] = 'e72174d60e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
